config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :items do 
		member do
			# reference to complete method in items_controller and PATCH route
			patch :complete
			patch :position_up
			patch :position_down
		end
	end
	root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user

	def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, -> { order(position: :asc) }	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy]

	def index
		if user_signed_in?
			@items = Item.where(:user_id => current_user.id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@item = current_user.items.build
	end

	def create
		@item = current_user.items.build(items_params)
		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @item.update(items_params)
			redirect_to item_path(@item)
		else
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to root_path
	end

	def complete
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path
	end

	def position_up
		@item = Item.find(params[:id])
		@item.move_higher.update_attribute(:psoition)
		redirect_to root_path
	end

	def position_down
		@item = Item.find(params[:id])
		@item.move_lower.update_attribute(:psoition)
		redirect_to root_path
	end


	private

	def items_params
		params.require(:item).permit(:title, :description)
	end

	def find_item
		@item = Item.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
	<%= f.input :title, label: "Item" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/items/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "My Checklist", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path, class: "active" %></li>
      <% if user_signed_in? %>
        <li><%= link_to "New Item", new_item_path, class: "active" %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% if current_user.present? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>


<!-- Unused navbar code -->

<!-- <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% if current_user.present? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to "New Item", new_item_path, class: "navbar-text navbar-link navbar-right" %>
      <% end %>
    </ul>
  </div>
</nav> -->


<!-- Bootstrap navbar code -->

<!-- <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav> -->

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">	
	<h1>Edit Checklist Item</h1>

	<%= render 'form' %>
</div>

app/views/items/index.html.erb
<% if user_signed_in? %>	

	<div class="col-md-6 col-md-offset-3">
		<% @items.each do |item| %>
			<% if item.completed? %>
				<div class="row item">

					<div class="col-md-8">
						<!-- strike tag = checked -->
						<h2 style="opacity: 0.5;"><strike><%= link_to item.title, item %></strike></h2>
						<p style="opacity: 0.5;"><%= item.description %></p>
						<p style="opacity: 0.5;">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
					</div>

					<ul class="list-inline">
						<div class="col-md-2">
							<p><%= link_to position_up_item_path(item), method: :patch do %></p>
								<i class="fas fa-lg fa-arrow-up"></i>
							<% end %>
						</div>

						<div class="col-md-2">
							<p><%= link_to position_down_item_path(item), method: :patch do %></p>
								<i class="fas fa-lg fa-arrow-down"></i>
							<% end %>
						</div>		

						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-lg fa-check"></i>
							<% end %>
						</div>

						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-lg fa-trash"></i>
							<% end %>
						</div>
					</ul>
				</div>

			<% else %>

				<div class="row item">

					<div class="col-md-8">
						<h2><%= link_to item.title, item %></h2>
						<p><%= item.description %></p>
						<p>Created <%= time_ago_in_words(item.created_at) %> ago</p>
					</div>

					<ul class="list-inline">
						<div class="col-md-2">
							<p><%= link_to position_up_item_path(item), method: :patch do %></p>
								<i class="fas fa-lg fa-arrow-up"></i>
							<% end %>
						</div>

						<div class="col-md-2">
							<p><%= link_to position_down_item_path(item), method: :patch do %></p>
								<i class="fas fa-lg fa-arrow-down"></i>
							<% end %>
						</div>	

						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-lg fa-check"></i>
							<% end %>
						</div>

						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-lg fa-trash"></i>
							<% end %>
						</div>
					</ul>
				</div>

			<% end %>
		<% end %>
	</div>

<% else %>
	<%= render 'layouts/landing_page' %>
<% end %>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>New Checklist Item</h1>

	<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<h2><%= @item.title %></h2>
	<p><%= @item.description %></p>

	<%= link_to "Back", root_path %>
	<%= link_to "Edit", edit_item_path(@item) %>
	<%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/_landing_page.html.erb
<div class="jumbotron">
	<h1>Welcome to ListOn!</h1>
	<p>Your Checklist organizer</p>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListOn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <div class="navbar-header">
        <%= link_to "ListOn", root_path, class: "navbar-brand", id: "logo" %>
      </div>

      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "active" %></li>

        <% if user_signed_in? %>
          <li><%= link_to "New Item", new_item_path, class: "active" %></li>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>

      </ul>

    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">

    <%= yield %>
    
  </div>

  

  </body>
</html>